#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Romain Behar

fichierFANTOIR = 'FANTOIR0119'
codeCommune = '690019'


voies = {
    'ACH': 'ancien chemin',
    'AER': 'aérodrome',
    'AERG': 'aérogare',
    'AGL': 'agglomeration',
    'AIRE': 'aire',
    'ALL': 'allée',
    'ANGL': 'angle',
    'ARC': 'arcade',
    'ART': 'ancienne route',
    'AUT': 'autoroute',
    'AV': 'avenue',
    'BASE': 'base',
    'BD': 'boulevard',
    'BER': 'berge',
    'BORD': 'bord',
    'BRE': 'barrière',
    'BRG': 'bourg',
    'BRTL': 'bretelle',
    'BSN': 'bassin',
    'CAE': 'carriera',
    'CALL': 'calle/callada',
    'CAMI': 'camin',
    'CAMP': 'camp',
    'CAN': 'canal',
    'CAR': 'carrefour',
    'CARE': 'carrière',
    'CASR': 'caserne',
    'CC': 'chemin communal',
    'CD': 'chemin departemental',
    'CF': 'chemin forestier',
    'CHA': 'chasse',
    'CHE': 'chemin',
    'CHEM': 'cheminement',
    'CHL': 'chalet',
    'CHP': 'champ',
    'CHS': 'chaussée',
    'CHT': 'château',
    'CHV': 'chemin vicinal',
    'CITE': 'cité',
    'CIVE': 'coursive',
    'CLOS': 'clos',
    'CLR': 'couloir',
    'COIN': 'coin',
    'COL': 'col',
    'COR': 'corniche',
    'CORO': 'coron',
    'COTE': 'côte',
    'COUR': 'cour',
    'CPG': 'camping',
    'CR': 'chemin rural',
    'CRS': 'cours',
    'CRX': 'croix',
    'CTR': 'contour',
    'CTRE': 'centre',
    'DARS': 'darse/darce',
    'DEVI': 'déviation',
    'DIG': 'digue',
    'DOM': 'domaine',
    'DRA': 'draille',
    'DSC': 'descente',
    'ECA': 'écart',
    'ECL': 'écluse',
    'EMBR': 'embranchement',
    'EMP': 'emplacement',
    'ENC': 'enclos',
    'ENV': 'enclave',
    'ESC': 'escalier',
    'ESP': 'esplanade',
    'ESPA': 'espace',
    'ETNG': 'étang',
    'FD': 'fond',
    'FG': 'faubourg',
    'FON': 'fontaine',
    'FOR': 'forêt',
    'FORT': 'fort',
    'FOS': 'fosse',
    'FRM': 'ferme',
    'GAL': 'galerie',
    'GARE': 'gare',
    'GBD': 'grand boulevard',
    'GPL': 'grande place',
    'GR': 'grande rue',
    'GREV': 'grêve',
    'HAB': 'habitation',
    'HAM': 'hameau',
    'HIP': 'hippodrome',
    'HLE': 'halle',
    'HLG': 'halage',
    'HLM': 'HLM',
    'HTR': 'hauteur',
    'ILE': 'île',
    'ILOT': 'îlot',
    'IMP': 'impasse',
    'JARD': 'jardin',
    'JTE': 'jetée',
    'LAC': 'lac',
    'LEVE': 'levée',
    'LICE': 'lices',
    'LIGN': 'ligne',
    'LOT': 'lotissement',
    'MAIL': 'mail',
    'MAIS': 'maison',
    'MAR': 'marché',
    'MARE': 'mare',
    'MAS': 'mas',
    'MNE': 'morne',
    'MRN': 'marina',
    'MTE': 'montée',
    'NTE': 'nouvelle route',
    'PAE': 'petite avenue',
    'PARC': 'parc',
    'PAS': 'passage',
    'PASS': 'passe',
    'PCH': 'petit chemin',
    'PCHE': 'porche',
    'PHAR': 'phare',
    'PIST': 'piste',
    'PKG': 'parking',
    'PL': 'place',
    'PLA': 'placa',
    'PLAG': 'plage',
    'PLAN': 'plan',
    'PLCI': 'placis',
    'PLE': 'passerelle',
    'PLN': 'plaine',
    'PLT': 'plateau',
    'PNT': 'pointe',
    'PONT': 'pont',
    'PORQ': 'portique',
    'PORT': 'port',
    'POST': 'poste',
    'POT': 'poterne',
    'PROM': 'promenade',
    'PRT': 'petite route',
    'PRV': 'parvis',
    'PTA': 'petite alleé',
    'PTE': 'porte',
    'PTR': 'petite rue',
    'PTTE': 'placette',
    'QUA': 'quartier',
    'QUAI': 'quai',
    'RAC': 'raccourci',
    'REM': 'rempart',
    'RES': 'résidence',
    'RIVE': 'rive',
    'RLE': 'ruelle',
    'ROC': 'rocade',
    'RPE': 'rampe',
    'RPT': 'rond-point',
    'RTD': 'rotonde',
    'RTE': 'route',
    'RUE': 'rue',
    'RUET': 'ruette',
    'RUIS': 'ruisseau',
    'RULT': 'ruellette',
    'RVE': 'ravine',
    'SAS': 'sas',
    'SEN': 'sentier;sente',
    'SQ': 'square',
    'STDE': 'stade',
    'TER': 'terre',
    'TOUR': 'tour',
    'TPL': 'terre-plein',
    'TRA': 'traverse',
    'TRAB': 'traboule',
    'TRN': 'terrain',
    'TRT': 'tertre',
    'TSSE': 'terrasse',
    'TUN': 'tunnel',
    'VAL': 'val',
    'VALL': 'vallon/vallée',
    'VC': 'voie communale',
    'VCHE': 'vieux chemin',
    'VEN': 'venelle',
    'VGE': 'village',
    'VIA': 'via',
    'VIAD': 'viaduc',
    'VIL': 'ville',
    'VLA': 'villa',
    'VOIE': 'voie',
    'VOIR': 'voirie',
    'VOUT': 'voute',
    'VOY': 'voyeul',
    'VTE': 'vieille route',
    'ZA': 'ZA',
    'ZAC': 'ZAC',
    'ZAD': 'ZAD',
    'ZI': 'ZI',
    'ZONE': 'zone',
    'ZUP': 'ZUP',
}


with open(fichierFANTOIR, 'r') as f:
    for line in f:
        text = line.rstrip()
        if not text.startswith(codeCommune):
            continue

        fantoir = text[0:11]
        voie = text[11:15].rstrip()
        nom = text[15:41].rstrip()
        annulation = text[73].rstrip()
        typevoie = ''
        if len(text) > 107:
            typevoie = text[108].rstrip()
        caractere = ''
        if len(text) > 108:
            caractere = text[109].rstrip()

        if voie == 'LYON' or voie == 'N':
            continue

        if voie != '':
            if not voie in voies:
                print 'Type de voie inconnu: ' + voie
            else:
                voie = voies[voie]

        if nom != 'NON DESIGNEE':
            print(fantoir + ';' + voie + ';' + nom + ';' + annulation + ';' + typevoie + ';' + caractere)
